name: Update resume in new PR
# on: repository_dispatch
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # if: github.event.action == 'update_resume'
        uses: actions/checkout@v1
      - name: Fetch New Resume and Push Branch
        # if: github.event.action == 'update_resume'
        uses: ./open-resume-pr
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      - name: Pull Request on Branch Push
        # if: github.event.action == 'update_resume'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: resume/
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: Updates Resume
