name: Fetch New Resume
# on: repository_dispatch
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # if: github.event.action == 'update_resume'
        uses: actions/checkout@v1
      - name: Fetch New Resume and Push Branch
        # if: github.event.action == 'update_resume'
        uses: ./commit-resume
        env:
          BRANCH: resume/update
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          PULL_REQUEST_BODY: test
          PULL_REQUEST_TITLE: Resume
          PULL_REQUEST_BRANCH: main
