name: Update resume in new PR
# on: repository_dispatch
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # if: github.event.action == 'update_resume'
        uses: actions/checkout@v1
      - name: Fetch New Resume and Push Branch
        # if: github.event.action == 'update_resume'
        uses: ./open-resume-pr
      - name: Pull Request on Branch Push
        # if: github.event.action == 'update_resume'
        uses: vsoch/pull-request-action@1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
          BRANCH_PREFIX: update/
          PULL_REQUEST_BRANCH: master
