name: Update Resume on Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pull Request on Branch Push
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: resume/
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: Updates Resume
