name: Lint
on: [push]
jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: bun run lint
      - name: Prettier check
        run: npm run format:check
